In [4]:
import pandas as pd
gold_data = pd.read_csv("goldprices.csv")

In [5]:
gold_data.describe()

,Open,High,Low,Close,Adj Close,Volume
count,5205.000000,5205.000000,5205.000000,5205.000000,5205.000000,5205.000000
mean,1018.675312,1023.820096,1013.118867,1018.535524,1018.535524,4257.242651
std,490.316244,493.277232,486.969047,490.177751,490.177751,24536.337729
min,255.000000,256.100006,255.000000,255.100006,255.100006,0.000000
25%,485.600006,486.000000,486.000000,489.000000,489.000000,18.000000
50%,1174.599976,1180.300049,1168.300049,1174.599976,1174.599976,95.000000
75%,1334.500000,1341.400024,1326.900024,1335.099976,1335.099976,357.000000
max,2045.500000,2063.000000,2040.000000,2051.500000,2051.500000,386334.000000

In [6]:
gold_data.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2000-08-30,273.899994,273.899994,273.899994,273.899994,273.899994,0.0
1,2000-08-31,274.799988,278.299988,274.799988,278.299988,278.299988,0.0
2,2000-09-01,277.000000,277.000000,277.000000,277.000000,277.000000,0.0
3,2000-09-04,NaN,NaN,NaN,NaN,NaN,NaN
4,2000-09-05,275.799988,275.799988,275.799988,275.799988,275.799988,2.0

In [7]:
import yfinance as yf
tickers = {
    "Gold_YF": "GC=F",
    "DXY": "DX-Y.NYB",
    "TNX": "^TNX",
    "VIX": "^VIX"
}

data = {}

for name, ticker in tickers.items():
    df = yf.download(ticker, start="2000-08-30", interval="1d") #2000-08-30 is where gold YF starts from
    df = df[["Close"]]
    df.rename(columns={"Close": name}, inplace=True)
    data[name] = df

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [8]:
merged_df = pd.concat(data.values(), axis=1)
merged_df.columns = merged_df.columns.get_level_values(0)

In [9]:
merged_df.reset_index(inplace=True) 
merged_df.columns.name = "Index"

In [10]:
merged_df

Index       Date      Gold_YF         DXY    TNX        VIX
0     2000-08-30   273.899994  112.139999  5.800  17.690001
1     2000-08-31   278.299988  112.599998  5.729  16.840000
2     2000-09-01   277.000000  111.419998  5.675  17.530001
3     2000-09-05   275.799988  112.410004  5.683  19.820000
4     2000-09-06   274.200012  114.120003  5.712  20.790001
...          ...          ...         ...    ...        ...
6442  2026-03-02  5294.399902   98.379997  4.048  21.440001
6443  2026-03-03  5107.399902   99.050003  4.056  23.570000
6444  2026-03-04  5120.200195   98.769997  4.080  21.150000
6445  2026-03-05  5065.299805   99.320000  4.146  23.750000
6446  2026-03-06  5146.000000   98.950996  4.142  26.059999

[6447 rows x 5 columns]

In [11]:
#merged_df.to_csv("gold_macro_yfinance_2000.csv")

In [12]:
gold_data["Date"] = pd.to_datetime(gold_data["Date"])
merged_df["Date"] = pd.to_datetime(merged_df["Date"])

In [13]:
gold_merged = pd.merge(gold_data, merged_df, on="Date", how="inner")

In [14]:
gold_merged[["Date", "Close", "Gold_YF"]]

           Date        Close      Gold_YF
0    2000-08-30   273.899994   273.899994
1    2000-08-31   278.299988   278.299988
2    2000-09-01   277.000000   277.000000
3    2000-09-05   275.799988   275.799988
4    2000-09-06   274.200012   274.200012
...         ...          ...          ...
5273 2021-07-12  1805.500000  1805.500000
5274 2021-07-13  1809.400024  1809.400024
5275 2021-07-14  1824.300049  1824.300049
5276 2021-07-15  1828.400024  1828.400024
5277 2021-07-16  1814.500000  1814.500000

[5278 rows x 3 columns]

In [15]:
merged_df.describe()

Index,Date,Gold_YF,DXY,TNX,VIX
count,6447,6402.000000,6442.000000,6410.000000,6416.000000
mean,2013-05-20 22:50:32.107957248,1276.716197,92.543080,3.241408,19.749797
min,2000-08-30 00:00:00,255.100006,71.330002,0.499000,9.140000
25%,2006-12-20 12:00:00,651.849991,82.552502,2.217000,13.940000
50%,2013-05-17 00:00:00,1251.200012,93.050003,3.356000,17.585000
75%,2019-10-09 12:00:00,1696.325012,99.519997,4.247750,23.030001
max,2026-03-06 00:00:00,5318.399902,120.900002,5.892000,82.690002
std,NaN,787.115666,11.165475,1.217773,8.420890

In [16]:
merged_df

Index       Date      Gold_YF         DXY    TNX        VIX
0     2000-08-30   273.899994  112.139999  5.800  17.690001
1     2000-08-31   278.299988  112.599998  5.729  16.840000
2     2000-09-01   277.000000  111.419998  5.675  17.530001
3     2000-09-05   275.799988  112.410004  5.683  19.820000
4     2000-09-06   274.200012  114.120003  5.712  20.790001
...          ...          ...         ...    ...        ...
6442  2026-03-02  5294.399902   98.379997  4.048  21.440001
6443  2026-03-03  5107.399902   99.050003  4.056  23.570000
6444  2026-03-04  5120.200195   98.769997  4.080  21.150000
6445  2026-03-05  5065.299805   99.320000  4.146  23.750000
6446  2026-03-06  5146.000000   98.950996  4.142  26.059999

[6447 rows x 5 columns]

In [17]:
merged_df.isna().sum()

Index
Date        0
Gold_YF    45
DXY         5
TNX        37
VIX        31
dtype: int64

In [18]:
merged_df[merged_df.isna().any(axis=1)]

Index       Date      Gold_YF         DXY    TNX        VIX
60    2000-11-23          NaN  118.089996    NaN        NaN
61    2000-11-24          NaN  118.480003  5.622  26.000000
95    2001-01-15          NaN  109.970001    NaN        NaN
120   2001-02-19          NaN  111.919998    NaN        NaN
215   2001-07-04          NaN  119.910004    NaN        NaN
258   2001-09-03          NaN  113.669998    NaN        NaN
264   2001-09-14   290.200012         NaN    NaN        NaN
313   2001-11-22          NaN  117.300003    NaN        NaN
314   2001-11-23          NaN  117.330002  4.991  23.250000
335   2001-12-24          NaN  117.940002  5.132  22.620001
353   2002-01-21          NaN  117.660004    NaN        NaN
373   2002-02-18          NaN  118.760002    NaN        NaN
442   2002-05-27          NaN  113.000000    NaN        NaN
470   2002-07-04          NaN  107.339996    NaN        NaN
471   2002-07-05          NaN  107.669998  4.864  27.110001
574   2002-11-28          NaN  106.540001    NaN        NaN
575   2002-11-29          NaN  106.410004  4.213  27.500000
724   2003-07-04          NaN   94.550003    NaN        NaN
765   2003-09-01          NaN   98.000000    NaN        NaN
816   2003-11-11   388.100006   93.099998    NaN  17.540001
828   2003-11-28          NaN   90.209999  4.320  16.320000
847   2003-12-26          NaN   87.629997  4.148  17.450001
851   2004-01-02          NaN   86.919998  4.373  18.219999
862   2004-01-19          NaN   87.660004    NaN        NaN
882   2004-02-16          NaN   85.470001    NaN        NaN
964   2004-06-11          NaN   90.010002    NaN        NaN
980   2004-07-05          NaN   88.230003    NaN        NaN
1025  2004-09-06          NaN   89.529999    NaN        NaN
1083  2004-11-25          NaN   82.180000    NaN        NaN
1084  2004-11-26          NaN   81.779999  4.238  12.780000
1104  2004-12-24          NaN   81.220001    NaN        NaN
1109  2004-12-31          NaN   80.849998  4.216  13.290000
1120  2005-01-17          NaN   83.059998    NaN        NaN
1145  2005-02-21          NaN   83.550003    NaN        NaN
1171  2005-03-30          NaN   84.290001  4.558  13.640000
1192  2005-04-28          NaN   84.349998  4.173  16.860001
1235  2005-06-29          NaN   89.110001  3.990  11.770000
1238  2005-07-04          NaN   90.430000    NaN        NaN
1307  2005-10-10   475.100006   89.459999    NaN  15.550000
1331  2005-11-11   468.299988   91.980003    NaN  11.630000
1340  2005-11-25          NaN   92.040001  4.431  10.880000
1490  2006-07-03          NaN   85.180000  5.151  13.050000
1534  2006-09-04   624.400024         NaN    NaN        NaN
1559  2006-10-09   578.400024   86.519997    NaN  11.680000
1592  2006-11-23          NaN   84.480003    NaN        NaN
1594  2006-11-27          NaN   83.510002  4.538  12.300000
1618  2007-01-02   635.200012   83.199997    NaN        NaN
2569  2010-10-11  1353.300049   77.440002    NaN  18.959999
3895  2016-01-18          NaN   99.120003    NaN        NaN
4080  2016-10-10          NaN         NaN  1.723  13.380000
4104  2016-11-11          NaN         NaN    NaN  14.170000
4407  2018-01-29          NaN   89.309998  2.699  13.840000
6155  2025-01-09  2683.800049  109.180000    NaN        NaN
6249  2025-05-26          NaN   98.930000    NaN        NaN
6277  2025-07-04  3332.500000         NaN    NaN        NaN

### We observe that there are some rows where gold_yf populates but DXY, TNX, VIX don't, we neeed to forward fill these values so that the last known value is still in place.,

In [19]:
merged_df.fillna(method="ffill", inplace=True)

C:\Users\huzef\AppData\Local\Temp\ipykernel_16812\1686597910.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  merged_df.fillna(method="ffill", inplace=True)

In [20]:
merged_df.isna().sum()

Index
Date       0
Gold_YF    0
DXY        0
TNX        0
VIX        0
dtype: int64

In [21]:
merged_df["Gold_return_1d"] = merged_df["Gold_YF"].pct_change()

In [22]:
merged_df

Index       Date      Gold_YF         DXY    TNX        VIX  Gold_return_1d
0     2000-08-30   273.899994  112.139999  5.800  17.690001             NaN
1     2000-08-31   278.299988  112.599998  5.729  16.840000        0.016064
2     2000-09-01   277.000000  111.419998  5.675  17.530001       -0.004671
3     2000-09-05   275.799988  112.410004  5.683  19.820000       -0.004332
4     2000-09-06   274.200012  114.120003  5.712  20.790001       -0.005801
...          ...          ...         ...    ...        ...             ...
6442  2026-03-02  5294.399902   98.379997  4.048  21.440001        0.012217
6443  2026-03-03  5107.399902   99.050003  4.056  23.570000       -0.035320
6444  2026-03-04  5120.200195   98.769997  4.080  21.150000        0.002506
6445  2026-03-05  5065.299805   99.320000  4.146  23.750000       -0.010722
6446  2026-03-06  5146.000000   98.950996  4.142  26.059999        0.015932

[6447 rows x 6 columns]

In [23]:
merged_df["Gold_YF"].shift(5)[:10]

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
5    273.899994
6    278.299988
7    277.000000
8    275.799988
9    274.200012
Name: Gold_YF, dtype: float64

In [24]:
merged_df["Gold_forward_5d"] = ((merged_df["Gold_YF"].shift(-5) - merged_df["Gold_YF"])/merged_df["Gold_YF"])

In [25]:
merged_df

Index,Date,Gold_YF,DXY,TNX,VIX,Gold_return_1d,Gold_forward_5d
0,2000-08-30,273.899994,112.139999,5.800,17.690001,NaN,0.000365
1,2000-08-31,278.299988,112.599998,5.729,16.840000,0.016064,-0.017966
2,2000-09-01,277.000000,111.419998,5.675,17.530001,-0.004671,-0.014079
3,2000-09-05,275.799988,112.410004,5.683,19.820000,-0.004332,-0.010515
4,2000-09-06,274.200012,114.120003,5.712,20.790001,-0.005801,-0.005106
...,...,...,...,...,...,...,...
6442,2026-03-02,5294.399902,98.379997,4.048,21.440001,0.012217,NaN
6443,2026-03-03,5107.399902,99.050003,4.056,23.570000,-0.035320,NaN
6444,2026-03-04,5120.200195,98.769997,4.080,21.150000,0.002506,NaN
6445,2026-03-05,5065.299805,99.320000,4.146,23.750000,-0.010722,NaN
6446,2026-03-06,5146.000000,98.950996,4.142,26.059999,0.015932,NaN

In [27]:
import numpy as np
prices = merged_df["Gold_YF"].values
forward_5d = (prices[5:] - prices[:-5]) / prices[:-5]
merged_df["new_test_5dF"] = np.nan

In [28]:
merged_df.loc[merged_df.index[:len(forward_5d)], "new_test_5dF"] = forward_5d

In [29]:
merged_df[5500:6000]

Index,Date,Gold_YF,DXY,TNX,VIX,Gold_return_1d,Gold_forward_5d,new_test_5dF
5500,2022-06-01,1843.300049,102.550003,2.931,25.690001,0.000326,0.004666,0.004666
5501,2022-06-02,1866.500000,101.769997,2.913,24.719999,0.012586,-0.009483,-0.009483
5502,2022-06-03,1845.400024,102.139999,2.957,24.790001,-0.011305,0.014143,0.014143
5503,2022-06-06,1839.199951,102.440002,3.038,25.070000,-0.003360,-0.006090,-0.006090
5504,2022-06-07,1847.500000,102.320000,2.972,24.020000,0.004513,-0.020568,-0.020568
...,...,...,...,...,...,...,...,...
5995,2024-05-21,2421.699951,104.660004,4.414,11.860000,-0.005013,-0.033613,-0.033613
5996,2024-05-22,2389.199951,104.940002,4.434,12.290000,-0.013420,-0.019379,-0.019379
5997,2024-05-23,2335.000000,105.110001,4.475,12.770000,-0.022685,-0.005182,-0.005182
5998,2024-05-24,2332.500000,104.720001,4.467,11.930000,-0.001071,0.006045,0.006045
5999,2024-05-28,2355.199951,104.610001,4.542,12.920000,0.009732,-0.012610,-0.012610

In [30]:
def target(x):
    if x >= 0.02:
        return 1
    elif x <= -0.02:
        return -1
    else:
        return 0

In [31]:
merged_df["Target"] = merged_df["Gold_forward_5d"].apply(target)

In [32]:
merged_df["Target"].value_counts(normalize=True)

Target
 0    0.646192
 1    0.207228
-1    0.146580
Name: proportion, dtype: float64

In [33]:
# Easier Method
merged_df["Target"] = 0
merged_df.loc[merged_df["Gold_forward_5d"] >= 0.02, "Target"] = 1
merged_df.loc[merged_df["Gold_forward_5d"] <= -0.02, "Target"] = -1

In [34]:
merged_df

Index,Date,Gold_YF,DXY,TNX,VIX,Gold_return_1d,Gold_forward_5d,new_test_5dF,Target
0,2000-08-30,273.899994,112.139999,5.800,17.690001,NaN,0.000365,0.000365,0
1,2000-08-31,278.299988,112.599998,5.729,16.840000,0.016064,-0.017966,-0.017966,0
2,2000-09-01,277.000000,111.419998,5.675,17.530001,-0.004671,-0.014079,-0.014079,0
3,2000-09-05,275.799988,112.410004,5.683,19.820000,-0.004332,-0.010515,-0.010515,0
4,2000-09-06,274.200012,114.120003,5.712,20.790001,-0.005801,-0.005106,-0.005106,0
...,...,...,...,...,...,...,...,...,...
6442,2026-03-02,5294.399902,98.379997,4.048,21.440001,0.012217,NaN,NaN,0
6443,2026-03-03,5107.399902,99.050003,4.056,23.570000,-0.035320,NaN,NaN,0
6444,2026-03-04,5120.200195,98.769997,4.080,21.150000,0.002506,NaN,NaN,0
6445,2026-03-05,5065.299805,99.320000,4.146,23.750000,-0.010722,NaN,NaN,0
6446,2026-03-06,5146.000000,98.950996,4.142,26.059999,0.015932,NaN,NaN,0

### Try: Option 2 — Volatility-Adjusted Threshold (Advanced)

In [35]:
merged_df["Target_1.5"] = 0
merged_df.loc[merged_df["Gold_forward_5d"] >= 0.015, "Target_1.5"] = 1
merged_df.loc[merged_df["Gold_forward_5d"] <= -0.015, "Target_1.5"] = -1

In [36]:
merged_df["Target_1.5"].value_counts(normalize=True)

Target_1.5
 0    0.517760
 1    0.277183
-1    0.205057
Name: proportion, dtype: float64

In [37]:
merged_df["Gold_forward_5d"].quantile([0.7, 0.75, 0.8, 0.85, 0.9])

0.70    0.013613
0.75    0.016822
0.80    0.020479
0.85    0.024858
0.90    0.030189
Name: Gold_forward_5d, dtype: float64

In [39]:
ticker = yf.Ticker("GBP=X")

In [42]:
ticker.history()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-02-06 00:00:00+00:00,0.73958,0.74020,0.73445,0.739600,0,0.0,0.0
2026-02-09 00:00:00+00:00,0.73483,0.73591,0.73037,0.734810,0,0.0,0.0
2026-02-10 00:00:00+00:00,0.73083,0.73240,0.73000,0.730810,0,0.0,0.0
2026-02-11 00:00:00+00:00,0.73350,0.73424,0.72924,0.733430,0,0.0,0.0
2026-02-12 00:00:00+00:00,0.73401,0.73500,0.73146,0.733999,0,0.0,0.0
2026-02-13 00:00:00+00:00,0.73424,0.73572,0.73280,0.734200,0,0.0,0.0
2026-02-16 00:00:00+00:00,0.73274,0.73383,0.73193,0.732720,0,0.0,0.0
2026-02-17 00:00:00+00:00,0.73375,0.74085,0.73370,0.733800,0,0.0,0.0
2026-02-18 00:00:00+00:00,0.73724,0.73885,0.73625,0.737220,0,0.0,0.0
2026-02-19 00:00:00+00:00,0.74099,0.74431,0.73978,0.740970,0,0.0,0.0
2026-02-20 00:00:00+00:00,0.74291,0.74425,0.73996,0.742880,0,0.0,0.0
2026-02-23 00:00:00+00:00,0.73917,0.74196,0.73879,0.738920,0,0.0,0.0
2026-02-24 00:00:00+00:00,0.74094,0.74231,0.73869,0.740910,0,0.0,0.0
2026-02-25 00:00:00+00:00,0.74094,0.74118,0.73794,0.740880,0,0.0,0.0
2026-02-26 00:00:00+00:00,0.73756,0.74090,0.73670,0.737570,0,0.0,0.0
2026-02-27 00:00:00+00:00,0.74116,0.74395,0.74044,0.741210,0,0.0,0.0
2026-03-02 00:00:00+00:00,0.74585,0.75093,0.74313,0.745900,0,0.0,0.0
2026-03-03 00:00:00+00:00,0.74577,0.75444,0.74487,0.745680,0,0.0,0.0
2026-03-04 00:00:00+00:00,0.74889,0.75157,0.74601,0.748860,0,0.0,0.0
2026-03-05 00:00:00+00:00,0.74797,0.75181,0.74703,0.747970,0,0.0,0.0
2026-03-06 00:00:00+00:00,0.74918,0.75115,0.74577,0.745850,0,0.0,0.0